-- REV22 greenfield baseline: 019_grant_matrix.sql
-- Consolidated from migrations_archive_rev19 (000-053)

-- SINGLE SSOT for EXECUTE and view grants

grant execute on function platform._apply_platform_admin_rls(regclass) to service_role;
grant execute on function platform._apply_tenant_rls(regclass) to service_role;
grant execute on function platform._apply_tenant_rls_select_only(regclass) to service_role;
grant execute on function platform.apply_payment_status(uuid, text, text, text, text, jsonb) to service_role;
grant execute on function platform.bind_operation_context_type_column() to service_role;
grant execute on function platform.complete_notification_delivery(uuid, boolean, jsonb) to service_role;
grant execute on function platform.create_monthly_partition(text, date) to service_role;
grant execute on function platform.create_vault_secret(text, text, text) to service_role;
grant execute on function platform.current_role() to authenticated, service_role;
grant execute on function platform.current_tenant_id() to authenticated, service_role;
grant execute on function platform.dispatch_http_request(text, text, jsonb, jsonb, int) to service_role;
grant execute on function platform.drop_old_log_partitions(text, interval) to service_role;
grant execute on function platform.enable_realtime(regclass) to service_role;
grant execute on function platform.enforce_payment_intent_target_tenant() to service_role;
grant execute on function platform.enqueue_http_delivery(uuid, text, text, jsonb, jsonb, text, text) to service_role;
grant execute on function platform.enqueue_shipment_dispatch(uuid, uuid, jsonb) to service_role;
grant execute on function platform.ensure_log_partitions(int) to service_role;
grant execute on function platform.ensure_pg_cron_jobs() to service_role;
grant execute on function platform.execution_watchdog() to service_role;
grant execute on function platform.fetch_external_webhook_batch(int) to service_role;
grant execute on function platform.fetch_integration_queue_batch(int) to service_role;
grant execute on function platform.fetch_next_command() to service_role;
grant execute on function platform.fetch_notification_batch(int) to service_role;
grant execute on function platform.fetch_retry_task_batch(int) to service_role;
grant execute on function platform.fetch_shipment_dispatch_batch(int) to service_role;
grant execute on function platform.get_device_command_context(uuid, uuid) to service_role;
grant execute on function platform.get_vault_secret(text) to service_role;
grant execute on function platform.handle_new_auth_user() to service_role;
grant execute on function platform.has_permission(text) to authenticated, service_role;
grant execute on function platform.has_role(text) to authenticated, service_role;
grant execute on function platform.has_tenant_access(uuid) to authenticated, service_role;
grant execute on function platform.has_tenant_membership(uuid, uuid) to authenticated, service_role;
grant execute on function platform.ingest_external_webhook(text, text, text, jsonb, uuid, text) to service_role;
grant execute on function platform.ingest_shipment_tracking_event(text, text, uuid, text, timestamptz, uuid, text, jsonb) to service_role;
grant execute on function platform.is_admin() to authenticated, service_role;
grant execute on function platform.is_owner() to authenticated, service_role;
grant execute on function platform.is_platform_admin() to authenticated, service_role;
grant execute on function platform.is_support() to authenticated, service_role;
grant execute on function platform.log_audit(text, text, uuid, jsonb) to service_role;
grant execute on function platform.log_event(text, text, jsonb, text, uuid, uuid) to service_role;
grant execute on function platform.log_operation(text, text, text, uuid, jsonb, jsonb, jsonb, uuid, text) to service_role;
grant execute on function platform.mark_integration_queue_item(uuid, text, jsonb) to service_role;
grant execute on function platform.mark_retry_task(uuid, text, int, text) to service_role;
grant execute on function platform.mark_shipment_dispatch_failed(uuid, jsonb, int, int) to service_role;
grant execute on function platform.mark_shipment_dispatched(uuid, text, text) to service_role;
grant execute on function platform.move_to_dlq(uuid, text, jsonb) to service_role;
grant execute on function platform.process_device_command_batch(int, text) to service_role;
grant execute on function platform.process_external_webhook(uuid) to service_role;
grant execute on function platform.process_external_webhook_batch(int) to service_role;
grant execute on function platform.process_integration_queue() to service_role;
grant execute on function platform.process_integration_queue_batch(int) to service_role;
grant execute on function platform.process_notification_batch(int) to service_role;
grant execute on function platform.process_payment_webhook(uuid) to service_role;
grant execute on function platform.process_retry_task_batch(int) to service_role;
grant execute on function platform.process_retry_tasks() to service_role;
grant execute on function platform.process_shipment_dispatch_batch(int) to service_role;
grant execute on function platform.process_shipment_dispatch_queue() to service_role;
grant execute on function platform.publish_internal_event(text, text, jsonb, uuid) to service_role;
grant execute on function platform.purge_expired_logs() to service_role;
grant execute on function platform.push_integration_event(text, text, jsonb) to service_role;
grant execute on function platform.run_platform_cron_tick() to service_role;
grant execute on function platform.run_platform_daily_maintenance() to service_role;
grant execute on function platform.schedule_retry_task(text, text, uuid, jsonb, text) to service_role;
grant execute on function platform.storage_tenant_from_path(text) to authenticated, service_role;
grant execute on function platform.storage_user_from_path(text) to authenticated, service_role;
grant execute on function platform.sync_http_request(text, text, text, text, int) to service_role;
grant execute on function platform.sync_service_activation_state() to service_role;
grant execute on function platform.update_device_command_status(uuid, text, text, jsonb, jsonb) to service_role;
grant execute on function platform.upsert_vault_secret(text, text, text) to service_role;
grant execute on function public._apply_public_tenant_rls(regclass) to service_role;
grant execute on function public.assign_device(uuid, uuid) to authenticated, service_role;
grant execute on function public.assign_device_to_room(uuid, uuid) to authenticated, service_role;
grant execute on function public.auth_api(text, jsonb) to authenticated, service_role;
grant execute on function public.auth_domain(text, jsonb) to authenticated, service_role;
grant execute on function public.auth_domain(text, jsonb) to service_role;
grant execute on function public.auth_domain_ext(text, jsonb) to authenticated, service_role;
grant execute on function public.auth_domain_ext_031(text, jsonb) to authenticated, service_role;
grant execute on function public.auth_invite_member(jsonb) to authenticated, service_role;
grant execute on function public.auth_invite_member(jsonb) to service_role;
grant execute on function public.auth_resolve_tenant_switch(uuid, uuid) to authenticated, service_role;
grant execute on function public.auth_switch_tenant(jsonb) to authenticated, service_role;
grant execute on function public.automation_api(text, jsonb) to authenticated, service_role;
grant execute on function public.automation_cancel_run(uuid) to authenticated, service_role;
grant execute on function public.automation_dispatch_event(text, jsonb) to authenticated, service_role;
grant execute on function public.automation_domain(text, jsonb) to authenticated, service_role;
grant execute on function public.automation_domain_ext(text, jsonb) to authenticated, service_role;
grant execute on function public.automation_enqueue_notification(jsonb) to authenticated, service_role;
grant execute on function public.automation_start_run(uuid, public.automation_trigger_type, jsonb) to authenticated, service_role;
grant execute on function public.booking_api(text, jsonb) to authenticated, service_role;
grant execute on function public.booking_calculate_access_window(uuid) to authenticated, service_role;
grant execute on function public.booking_compute_access_window(uuid) to authenticated, service_role;
grant execute on function public.booking_create_booking_access(jsonb) to authenticated, service_role;
grant execute on function public.booking_create_booking_access(jsonb) to service_role;
grant execute on function public.booking_domain(text, jsonb) to authenticated, service_role;
grant execute on function public.booking_generate_booking_access(uuid) to authenticated, service_role;
grant execute on function public.booking_regenerate_booking_access(uuid) to authenticated, service_role;
grant execute on function public.calculate_optimization_score(uuid) to authenticated, service_role;
grant execute on function public.change_subscription_plan(uuid) to authenticated, service_role;
grant execute on function public.commerce_api(text, jsonb) to authenticated, service_role;
grant execute on function public.commerce_change_subscription_plan(uuid) to authenticated, service_role;
grant execute on function public.commerce_create_subscription(uuid, public.subscription_tier) to authenticated, service_role;
grant execute on function public.commerce_domain(text, jsonb) to authenticated, service_role;
grant execute on function public.create_booking(uuid, date, date, text, text) to authenticated, service_role;
grant execute on function public.create_property(text, public.property_type, text, text) to authenticated, service_role;
grant execute on function public.create_subscription(uuid, public.subscription_tier) to authenticated, service_role;
grant execute on function public.crm_api(text, jsonb) to authenticated, service_role;
grant execute on function public.crm_domain(text, jsonb) to authenticated, service_role;
grant execute on function public.crm_soft_delete_row(regclass, uuid) to authenticated, service_role;
grant execute on function public.crm_soft_delete_row(regclass, uuid) to service_role;
grant execute on function public.devices_api(text, jsonb) to authenticated, service_role;
grant execute on function public.devices_assign_device_to_room(uuid, uuid) to authenticated, service_role;
grant execute on function public.devices_assign_device_to_room(uuid, uuid) to service_role;
grant execute on function public.devices_domain(text, jsonb) to authenticated, service_role;
grant execute on function public.devices_domain(text, jsonb) to service_role;
grant execute on function public.dispatch_fulfilment_order(uuid, jsonb) to authenticated, service_role;
grant execute on function public.edge_require_admin() to authenticated, service_role;
grant execute on function public.edge_require_manager() to authenticated, service_role;
grant execute on function public.edge_require_tenant() to authenticated, service_role;
grant execute on function public.edge_soft_delete_row(regclass, uuid) to authenticated, service_role;
grant execute on function public.edge_soft_delete_row(regclass, uuid) to service_role;
grant execute on function public.generate_lock_code(uuid, uuid, timestamptz, timestamptz) to authenticated, service_role;
grant execute on function public.generate_monetization_proposal(uuid, uuid) to authenticated, service_role;
grant execute on function public.get_onboarding_lifecycle(uuid) to authenticated, service_role;
grant execute on function public.has_tenant_access(uuid) to authenticated, service_role;
grant execute on function public.insert_event(text, jsonb, text, uuid, uuid) to authenticated, service_role;
grant execute on function public.integrations_api(text, jsonb) to authenticated, service_role;
grant execute on function public.integrations_complete_oauth(uuid, text, text) to service_role;
grant execute on function public.integrations_complete_oauth(uuid, text, text, text) to service_role;
grant execute on function public.integrations_domain(text, jsonb) to authenticated, service_role;
grant execute on function public.integrations_domain(text, jsonb) to service_role;
grant execute on function public.integrations_domain_ext(text, jsonb) to authenticated, service_role;
grant execute on function public.integrations_domain_ext(text, jsonb) to service_role;
grant execute on function public.integrations_exchange_oauth_tokens(uuid, text, text, text) to service_role;
grant execute on function public.integrations_oauth_complete(uuid, text, text) to service_role;
grant execute on function public.integrations_oauth_complete(uuid, text, text, text) to service_role;
grant execute on function public.integrations_oauth_complete_api(jsonb) to service_role;
grant execute on function public.integrations_oauth_url_encode(text) to authenticated, service_role;
grant execute on function public.integrations_resolve_oauth_state(text) to service_role;
grant execute on function public.integrations_start_oauth(jsonb) to authenticated, service_role;
grant execute on function public.is_platform_admin() to authenticated, service_role;
grant execute on function public.list_onboarding_lifecycle_transitions(uuid) to authenticated, service_role;
grant execute on function public.locks_api(text, jsonb) to authenticated, service_role;
grant execute on function public.locks_domain(text, jsonb) to authenticated, service_role;
grant execute on function public.log_event(text, jsonb) to authenticated, service_role;
grant execute on function public.logistics_api(text, jsonb) to authenticated, service_role;
grant execute on function public.logistics_dispatch_fulfilment_order(uuid, jsonb) to authenticated, service_role;
grant execute on function public.logistics_domain(text, jsonb) to authenticated, service_role;
grant execute on function public.logistics_domain(text, jsonb) to service_role;
grant execute on function public.monetization_api(text, jsonb) to authenticated, service_role;
grant execute on function public.monetization_domain(text, jsonb) to authenticated, service_role;
grant execute on function public.notification_api(text, jsonb) to authenticated, service_role;
grant execute on function public.notification_domain(text, jsonb) to authenticated, service_role;
grant execute on function public.onboarding_api(text, jsonb) to authenticated, service_role;
grant execute on function public.onboarding_domain(text, jsonb) to authenticated, service_role;
grant execute on function public.onboarding_lifecycle_apply_transition(uuid, public.onboarding_lifecycle_state, jsonb) to service_role;
grant execute on function public.onboarding_lifecycle_get(uuid) to service_role;
grant execute on function public.onboarding_lifecycle_list_transitions(uuid) to service_role;
grant execute on function public.onboarding_lifecycle_transition(uuid, public.onboarding_lifecycle_state, jsonb) to authenticated, service_role;
grant execute on function public.onboarding_step_update(uuid, public.onboarding_step_type, public.onboarding_step_status) to authenticated, service_role;
grant execute on function public.operations_api(text, jsonb) to authenticated, service_role;
grant execute on function public.operations_domain(text, jsonb) to authenticated, service_role;
grant execute on function public.optimization_api(text, jsonb) to authenticated, service_role;
grant execute on function public.optimization_domain(text, jsonb) to authenticated, service_role;
grant execute on function public.payment_api(text, jsonb) to authenticated, service_role;
grant execute on function public.payment_domain(text, jsonb) to authenticated, service_role;
grant execute on function public.payment_transition_status(uuid, public.payment_status, text, text, text, jsonb) to authenticated, service_role;
grant execute on function public.payment_transition_status(uuid, public.payment_status, text, text, text, jsonb) to service_role;
grant execute on function public.portal_api(text, jsonb) to authenticated, service_role;
grant execute on function public.portal_domain(text, jsonb) to authenticated, service_role;
grant execute on function public.preconfig_api(text, jsonb) to authenticated, service_role;
grant execute on function public.preconfig_domain(text, jsonb) to authenticated, service_role;
grant execute on function public.resolve_active_tenant(uuid, uuid) to authenticated, service_role;
grant select on public.v_automation_runs_overview to authenticated;
grant select on public.v_bookings_overview to authenticated;
grant select on public.v_crm_pipeline to authenticated;
grant select on public.v_devices_overview to authenticated;
grant select on public.v_onboarding_lifecycle_overview to authenticated;
grant select on public.v_onboarding_progress to authenticated;
grant select on public.v_properties_overview to authenticated;
grant select on public.v_subscription_overview to authenticated;
grant select on public.v_tenant_audit_overview to authenticated;
grant select on public.v_tenant_events_overview to authenticated;
revoke all on function platform._apply_platform_admin_rls(regclass) from public, authenticated;
revoke all on function platform._apply_tenant_rls(regclass) from public, authenticated;
revoke all on function platform._apply_tenant_rls_select_only(regclass) from public, authenticated;
revoke all on function platform._rev21_resolve_membership(uuid, uuid) from public, authenticated;
revoke all on function platform.apply_payment_status(uuid, text, text, text, text, jsonb) from public, authenticated;
revoke all on function platform.bind_operation_context_type_column() from public, authenticated;
revoke all on function platform.complete_notification_delivery(uuid, boolean, jsonb) from public, authenticated;
revoke all on function platform.create_monthly_partition(text, date) from public, authenticated;
revoke all on function platform.create_vault_secret(text, text, text) from public, authenticated;
revoke all on function platform.current_role() from public;
revoke all on function platform.current_tenant_id() from public;
revoke all on function platform.dispatch_http_request(text, text, jsonb, jsonb, int) from public, authenticated;
revoke all on function platform.drop_old_log_partitions(text, interval) from public, authenticated;
revoke all on function platform.enable_realtime(regclass) from public, authenticated;
revoke all on function platform.enforce_payment_intent_target_tenant() from public, authenticated;
revoke all on function platform.enqueue_http_delivery(uuid, text, text, jsonb, jsonb, text, text) from public, authenticated;
revoke all on function platform.enqueue_shipment_dispatch(uuid, uuid, jsonb) from public, authenticated;
revoke all on function platform.ensure_log_partitions(int) from public, authenticated;
revoke all on function platform.ensure_pg_cron_jobs() from public, authenticated;
revoke all on function platform.execution_watchdog() from public, authenticated;
revoke all on function platform.fetch_external_webhook_batch(int) from public, authenticated;
revoke all on function platform.fetch_integration_queue_batch(int) from public, authenticated;
revoke all on function platform.fetch_next_command() from public, authenticated;
revoke all on function platform.fetch_notification_batch(int) from public, authenticated;
revoke all on function platform.fetch_retry_task_batch(int) from public, authenticated;
revoke all on function platform.fetch_shipment_dispatch_batch(int) from public, authenticated;
revoke all on function platform.get_device_command_context(uuid, uuid) from public, authenticated;
revoke all on function platform.get_vault_secret(text) from public, authenticated;
revoke all on function platform.handle_new_auth_user() from public;
revoke all on function platform.has_permission(text) from public;
revoke all on function platform.has_role(text) from public;
revoke all on function platform.has_tenant_access(uuid) from public;
revoke all on function platform.has_tenant_membership(uuid, uuid) from public;
revoke all on function platform.ingest_external_webhook(text, text, text, jsonb, uuid, text) from public, authenticated;
revoke all on function platform.ingest_shipment_tracking_event(text, text, uuid, text, timestamptz, uuid, text, jsonb) from public, authenticated;
revoke all on function platform.is_admin() from public;
revoke all on function platform.is_owner() from public;
revoke all on function platform.is_platform_admin() from public;
revoke all on function platform.is_support() from public;
revoke all on function platform.log_audit(text, text, uuid, jsonb) from public, authenticated;
revoke all on function platform.log_event(text, text, jsonb, text, uuid, uuid) from public, authenticated;
revoke all on function platform.log_operation(text, text, text, uuid, jsonb, jsonb, jsonb, uuid, text) from public, authenticated;
revoke all on function platform.mark_integration_queue_item(uuid, text, jsonb) from public, authenticated;
revoke all on function platform.mark_retry_task(uuid, text, int, text) from public, authenticated;
revoke all on function platform.mark_shipment_dispatch_failed(uuid, jsonb, int, int) from public, authenticated;
revoke all on function platform.mark_shipment_dispatched(uuid, text, text) from public, authenticated;
revoke all on function platform.move_to_dlq(uuid, text, jsonb) from public, authenticated;
revoke all on function platform.process_device_command_batch(int, text) from public, authenticated;
revoke all on function platform.process_external_webhook(uuid) from public, authenticated;
revoke all on function platform.process_external_webhook_batch(int) from public, authenticated;
revoke all on function platform.process_integration_queue() from public, authenticated;
revoke all on function platform.process_integration_queue_batch(int) from public, authenticated;
revoke all on function platform.process_notification_batch(int) from public, authenticated;
revoke all on function platform.process_payment_webhook(uuid) from public, authenticated;
revoke all on function platform.process_retry_task_batch(int) from public, authenticated;
revoke all on function platform.process_retry_tasks() from public, authenticated;
revoke all on function platform.process_shipment_dispatch_batch(int) from public, authenticated;
revoke all on function platform.process_shipment_dispatch_queue() from public, authenticated;
revoke all on function platform.publish_internal_event(text, text, jsonb, uuid) from public, authenticated;
revoke all on function platform.purge_expired_logs() from public, authenticated;
revoke all on function platform.push_integration_event(text, text, jsonb) from public, authenticated;
revoke all on function platform.run_platform_cron_tick() from public, authenticated;
revoke all on function platform.run_platform_daily_maintenance() from public, authenticated;
revoke all on function platform.schedule_retry_task(text, text, uuid, jsonb, text) from public, authenticated;
revoke all on function platform.sync_http_request(text, text, text, text, int) from public, authenticated;
revoke all on function platform.sync_service_activation_state() from public, authenticated;
revoke all on function platform.update_device_command_status(uuid, text, text, jsonb, jsonb) from public, authenticated;
revoke all on function platform.upsert_vault_secret(text, text, text) from public, authenticated;
revoke all on function public._apply_public_tenant_rls(regclass) from public, authenticated;
revoke all on function public.assign_device(uuid, uuid) from public;
revoke all on function public.assign_device_to_room(uuid, uuid) from public;
revoke all on function public.auth_api(text, jsonb) from public;
revoke all on function public.auth_domain(text, jsonb) from public, authenticated;
revoke all on function public.auth_domain(text, jsonb) from public;
revoke all on function public.auth_domain_ext(text, jsonb) from public;
revoke all on function public.auth_domain_ext_031(text, jsonb) from public;
revoke all on function public.auth_invite_member(jsonb) from public, authenticated;
revoke all on function public.auth_invite_member(jsonb) from public;
revoke all on function public.auth_resolve_tenant_switch(uuid, uuid) from public;
revoke all on function public.auth_switch_tenant(jsonb) from public;
revoke all on function public.automation_api(text, jsonb) from public;
revoke all on function public.automation_cancel_run(uuid) from public;
revoke all on function public.automation_dispatch_event(text, jsonb) from public;
revoke all on function public.automation_domain(text, jsonb) from public;
revoke all on function public.automation_domain_ext(text, jsonb) from public;
revoke all on function public.automation_enqueue_notification(jsonb) from public;
revoke all on function public.automation_start_run(uuid, public.automation_trigger_type, jsonb) from public;
revoke all on function public.booking_api(text, jsonb) from public;
revoke all on function public.booking_calculate_access_window(uuid) from public;
revoke all on function public.booking_compute_access_window(uuid) from public;
revoke all on function public.booking_create_booking_access(jsonb) from public, authenticated;
revoke all on function public.booking_create_booking_access(jsonb) from public;
revoke all on function public.booking_domain(text, jsonb) from public;
revoke all on function public.booking_generate_booking_access(uuid) from public;
revoke all on function public.booking_regenerate_booking_access(uuid) from public;
revoke all on function public.calculate_optimization_score(uuid) from public;
revoke all on function public.change_subscription_plan(uuid) from public;
revoke all on function public.commerce_api(text, jsonb) from public;
revoke all on function public.commerce_change_subscription_plan(uuid) from public;
revoke all on function public.commerce_create_subscription(uuid, public.subscription_tier) from public;
revoke all on function public.commerce_domain(text, jsonb) from public;
revoke all on function public.create_booking(uuid, date, date, text, text) from public;
revoke all on function public.create_property(text, public.property_type, text, text) from public;
revoke all on function public.create_subscription(uuid, public.subscription_tier) from public;
revoke all on function public.crm_api(text, jsonb) from public;
revoke all on function public.crm_domain(text, jsonb) from public;
revoke all on function public.crm_soft_delete_row(regclass, uuid) from public, authenticated;
revoke all on function public.crm_soft_delete_row(regclass, uuid) from public;
revoke all on function public.devices_api(text, jsonb) from public;
revoke all on function public.devices_assign_device_to_room(uuid, uuid) from public, authenticated;
revoke all on function public.devices_assign_device_to_room(uuid, uuid) from public;
revoke all on function public.devices_domain(text, jsonb) from public, authenticated;
revoke all on function public.devices_domain(text, jsonb) from public;
revoke all on function public.dispatch_fulfilment_order(uuid, jsonb) from public;
revoke all on function public.edge_require_admin() from public;
revoke all on function public.edge_require_manager() from public;
revoke all on function public.edge_require_tenant() from public;
revoke all on function public.edge_soft_delete_row(regclass, uuid) from public, authenticated;
revoke all on function public.edge_soft_delete_row(regclass, uuid) from public;
revoke all on function public.generate_lock_code(uuid, uuid, timestamptz, timestamptz) from public;
revoke all on function public.generate_monetization_proposal(uuid, uuid) from public;
revoke all on function public.get_onboarding_lifecycle(uuid) from public;
revoke all on function public.has_tenant_access(uuid) from public;
revoke all on function public.insert_event(text, jsonb, text, uuid, uuid) from public;
revoke all on function public.integrations_api(text, jsonb) from public;
revoke all on function public.integrations_complete_oauth(uuid, text, text) from public;
revoke all on function public.integrations_complete_oauth(uuid, text, text, text) from public;
revoke all on function public.integrations_domain(text, jsonb) from public, authenticated;
revoke all on function public.integrations_domain(text, jsonb) from public;
revoke all on function public.integrations_domain_ext(text, jsonb) from public, authenticated;
revoke all on function public.integrations_domain_ext(text, jsonb) from public;
revoke all on function public.integrations_exchange_oauth_tokens(uuid, text, text, text) from public, authenticated;
revoke all on function public.integrations_oauth_complete(uuid, text, text) from public;
revoke all on function public.integrations_oauth_complete(uuid, text, text, text) from public;
revoke all on function public.integrations_oauth_complete_api(jsonb) from public, authenticated;
revoke all on function public.integrations_oauth_complete_api(jsonb) from public;
revoke all on function public.integrations_oauth_url_encode(text) from public;
revoke all on function public.integrations_resolve_oauth_state(text) from public;
revoke all on function public.integrations_start_oauth(jsonb) from public;
revoke all on function public.is_platform_admin() from public;
revoke all on function public.list_onboarding_lifecycle_transitions(uuid) from public;
revoke all on function public.locks_api(text, jsonb) from public;
revoke all on function public.locks_domain(text, jsonb) from public;
revoke all on function public.log_event(text, jsonb) from public;
revoke all on function public.logistics_api(text, jsonb) from public;
revoke all on function public.logistics_dispatch_fulfilment_order(uuid, jsonb) from public;
revoke all on function public.logistics_domain(text, jsonb) from public, authenticated;
revoke all on function public.logistics_domain(text, jsonb) from public;
revoke all on function public.monetization_api(text, jsonb) from public;
revoke all on function public.monetization_domain(text, jsonb) from public;
revoke all on function public.notification_api(text, jsonb) from public;
revoke all on function public.notification_domain(text, jsonb) from public;
revoke all on function public.onboarding_api(text, jsonb) from public;
revoke all on function public.onboarding_domain(text, jsonb) from public;
revoke all on function public.onboarding_lifecycle_apply_transition(uuid, public.onboarding_lifecycle_state, jsonb) from public;
revoke all on function public.onboarding_lifecycle_get(uuid) from public;
revoke all on function public.onboarding_lifecycle_list_transitions(uuid) from public;
revoke all on function public.onboarding_lifecycle_transition(uuid, public.onboarding_lifecycle_state, jsonb) from public;
revoke all on function public.onboarding_step_update(uuid, public.onboarding_step_type, public.onboarding_step_status) from public;
revoke all on function public.operations_api(text, jsonb) from public;
revoke all on function public.operations_domain(text, jsonb) from public;
revoke all on function public.optimization_api(text, jsonb) from public;
revoke all on function public.optimization_domain(text, jsonb) from public;
revoke all on function public.payment_api(text, jsonb) from public;
revoke all on function public.payment_domain(text, jsonb) from public;
revoke all on function public.payment_transition_status(uuid, public.payment_status, text, text, text, jsonb) from public, authenticated;
revoke all on function public.payment_transition_status(uuid, public.payment_status, text, text, text, jsonb) from public;
revoke all on function public.portal_api(text, jsonb) from public;
revoke all on function public.portal_domain(text, jsonb) from public;
revoke all on function public.preconfig_api(text, jsonb) from public;
revoke all on function public.preconfig_domain(text, jsonb) from public;
revoke all on function public.resolve_active_tenant(uuid, uuid) from public;
